### ISSUE TITLE
咨询帖

### ISSUE THREAD

**Issue by fangchuan** [NJUPT-Mirrors-Group/issues#1]
心血来潮google了一下南京大学的开源镜像网站，结果搜到了南邮的，本人2012级本科自动化院毕业，对母校的这个开源镜像网站很感兴趣，不知道现在都是学生团队作为一个娱乐项目在维护还是学校里网络处在维护。如果是学生团队在搞事情，恳求带我一个哈哈哈。

**Comment by guliujian** [comment]
学长你好 ，也很感谢你的关心，现在这个项目主要是一个学生团队在维护，同时也争取到了学校里的相应支持 ，为校内提供相应的服务等。

**Comment by fangchuan** [comment]
@guliujian 
Good Job!  不仅仅学生服务，同样也是把计算机相关的知识、资源以另一种课堂外的方式，更好的提供给同学们。中科大的开源镜像很不错，个人一直用上交的开源镜像，南邮早应该有一个像样的开源镜像网站，虽然我从未维护过网站，但我很希望上车哈哈哈，为母校的开源镜像添砖加瓦

**Comment by guliujian** [comment]
的确 ，对相关的推广 也是大有益处的，不过 我们暂时也遇到了一些推广上面的一些问题 ，所以也希望能得到大家的帮忙 。学长有什么即时通信的方式方便沟通吗 ？

**Comment by fangchuan** [comment]
@guliujian 
qq： 1457737815
电话 18362971877
随时欢迎致电！

**Comment by guliujian** [comment]
好的👌
