### ISSUE TITLE
miror request: BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [NJUPT-Mirrors-Group/issues#10]
## 开源项目名称及简介
Name: BioArchLinux
Introduction: Arch Community for Biologists & Arch Repository for Biological Software
Official web: https://bioarchlinux.org/
Github Repo: https://github.com/BioArchLinux/Packages
## 上游镜像名称及简介
Repo: repo.bioarchlinux.org
## 其他信息:
  * 30G
 ```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```

**Comment by kawhicurry** [comment]
您好，南邮镜像站已经开始同步该镜像，我们将和您一同关注南邮镜像站的同步状态。

当您确认镜像同步无误后，您可以关闭本issue。

如果您遇到了问题，请您在此issue下留言或发送邮件至mirrorrs@njupt.edu.cn。

**Comment by starsareintherose** [comment]
thanks
