### ISSUE TITLE
请求增加alpine linux软件源 

### ISSUE THREAD

**Issue by zhengziyi0117** [NJUPT-Mirrors-Group/issues#11]
## 开源项目名称及简介
**alpine linux** 
## 上游镜像名称及简介
**清华源alpine**:`https://mirrors.tuna.tsinghua.edu.cn/alpine/`
简介 Alpine 操作系统是一个面向安全的轻型 Linux 发行版。 它不同于通常 Linux 发行版， Alpine 采用了 musl libc 和 busybox 以减小系统的体积和运行时资源消耗，但功能上比 busybox 又完善的多，因此得到开源社区越来越多的青睐。
## 其他信息:
 * 镜像大小等
 1.92T

**Comment by kawhicurry** [comment]
We are synchronizing `alpine` now. Please take a look later.

**Comment by kawhicurry** [comment]
已经同步完成，此issue可以关闭了。
