### ISSUE TITLE
ALL MIRRORS' UPDATE WAS FAILED AT 11/18/2022. NOBODY NOTICED AT ALL?

### ISSUE THREAD

**Issue by Jordan-Haidee** [NJUPT-Mirrors-Group/issues#12]
## 其他信息:
  * 镜像大小等

**Comment by kawhicurry** [comment]
Thanks for reporting. We are investigating on it.

**Comment by kawhicurry** [comment]
@Tender-hjd  We've fix this problem.

In the matter of fact, all tasks has succeeded. But out sync tools report it as `failed` for some reason. You can check our service tomorrow and close this issue when you observe it works normally.

Again, thanks for reporting.

**Comment by Jordan-Haidee** [comment]
OK.



---Original---
From: "Kawhi ***@***.***&gt;
Date: Mon, Nov 21, 2022 16:43 PM
To: ***@***.***&gt;;
Cc: "Jiadong ***@***.******@***.***&gt;;
Subject: Re: [NJUPT-Mirrors-Group/issues] ALL MIRRORS' UPDATE WAS FAILED AT11/18/2022. NOBODY NOTICED AT ALL? (Issue #12)




 
@Tender-hjd  We've fix this problem.
 
In the matter of fact, all tasks has succeeded. But out sync tools report it as failed for some reason. You can check our service tomorrow and close this issue when you observe it works normally.
 
Again, thanks for reporting.

**Comment by Jordan-Haidee** [comment]
EVERYTHING IS RIGHT NOW!
