### ISSUE TITLE
有关速度的问题

### ISSUE THREAD

**Issue by conflucedd** [NJUPT-Mirrors-Group/issues#13]
今天看到南邮有镜像源很高兴，但是速度只有几十k，同时期ustc（科大）的源能跑满宽带，这也没法用啊

**Comment by kawhicurry** [comment]
同学你好，很高兴你使用南邮镜像源。不知道你是在校内还是校外使用哪些镜像源呢？

相对于ustc这样的大镜像站，南邮镜像站所拥有的物理资源（机器、带宽）是非常非常少的，所以我们目前的定位主要是服务校园网用户。

我刚刚也测试了一下，在校园网中的访问速度是很快的，在外网访问确实有些慢。在未来，我们还是希望优先满足校内用户的需求，然后**尽可能尝试优化外网的访问速度**，你觉得如何？

**Comment by conflucedd** [comment]
这当然很好，我是在校外访问的
