### ISSUE TITLE
请求添加 Debian ISO 安装镜像

### ISSUE THREAD

**Issue by ArcticLampyrid** [NJUPT-Mirrors-Group/issues#16]

**Comment by kawhicurry** [comment]
@ArcticLampyrid 下次提issue麻烦用下模版哈

debian-sd镜像大小：214G
参考：https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status
上游：rsync://mirrors.kernel.org/debian-cd/

**Comment by NKID00** [comment]
南邮镜像站的 debian-cd 镜像现已可用。之后会更新首页的下载链接并发布公告。

- https://mirrors.njupt.edu.cn/debian-cd/

**Comment by NKID00** [comment]
首页获取下载链接里的 Debian 安装镜像 ISO 现已可用。已发布公告。
