### ISSUE TITLE
请求添加ubuntu-ports源

### ISSUE THREAD

**Issue by invinciblesmalltree** [NJUPT-Mirrors-Group/issues#17]
ubuntu-ports镜像大小3.56T
参考：https://mirrors.nju.edu.cn/
上游：rsync://ports.ubuntu.com/ubuntu-ports/

**ubuntu-ports是ubuntu专门提供arm架构软件包的仓库，主要用于嵌入式设备。**

**Comment by NKID00** [comment]
南邮镜像站的 Ubuntu Ports 镜像现已可用。

- https://mirrors.njupt.edu.cn/ubuntu-ports/
