### ISSUE TITLE
请求添加ros和ros2源

### ISSUE THREAD

**Issue by invinciblesmalltree** [NJUPT-Mirrors-Group/issues#18]
ros源大小：103.63G
参考：https://mirrors.nju.edu.cn/
上游：rsync://packages.ros.org/ros/
清华源上游：rsync://mirrors.tuna.tsinghua.edu.cn/ros/

ros2源大小：92G
参考：https://mirrors.nju.edu.cn/
上游：rsync://packages.ros.org/ros2/
清华源上游：rsync://mirrors.tuna.tsinghua.edu.cn/ros2/

**ros是机器人操作系统，常用于飞控和智能车等场景。**

**Comment by NKID00** [comment]
南邮镜像站的 ROS 和 ROS2 镜像现已可用。

- https://mirrors.njupt.edu.cn/ros/
- https://mirrors.njupt.edu.cn/ros2/

**Comment by invinciblesmalltree** [comment]
我想写一个Help，后面写好再pr。

**Comment by NKID00** [comment]
> 我想写一个Help，后面写好再pr。

你好，谢谢你对南邮镜像站的支持。目前 MirrorZ 项目已经提供了 ROS 和 ROS2 镜像的帮助文档：

- https://help.mirrors.cernet.edu.cn/ros/
- https://help.mirrors.cernet.edu.cn/ros2/

我们可以复用这些文档。目前的问题是这些文档没有提供使用南邮镜像站的选项，我们之后计划在本地维护部署一份 MirrorZ 帮助文档的分支。

对这些文档内容的补充或者疑问可以提交到 [mirrorz-help 仓库](https://github.com/mirrorz-org/mirrorz-help)。
