### ISSUE TITLE
增加AOSP镜像

### ISSUE THREAD

**Issue by yjqwyc** [NJUPT-Mirrors-Group/issues#2]
## 开源项目名称及简介

AOSP(Android Open Source Project)

## 上游镜像名称及简介

 * [Android官方](https://android.googlesource.com/mirror)，建立镜像参考[官方文档](https://source.android.com/source/downloading#using-a-local-mirror)
  
> 如果网络环境限制无法访问GoogleSource，可以参考改用国内源，如[USTC](http://mirrors.ustc.edu.cn/aosp/)、[清华tuna](http://mirrors.tuna.tsinghua.edu.cn/aosp/)

## 其他信息:

* 镜像初始化可以使用tuna的[aosp-monthly](https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/)

> 需要先repo init --mirror [地址]，然后将monthly包内.repo/project-objects里的所有内容解压进repo init的目录的根目录（说不清楚，看代码）

```bash
mkdir aosp && cd aosp
repo init -u https://android.googlesource.com/mirror/manifest --mirror
wget -c https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-latest.tar
tar -xf aosp-latest.tar aosp/.repo/project-objects/* -C ./
repo sync
```

* 建议在http、https的基础上加上git协议

**Comment by guliujian** [comment]
经过大家的讨论，初步考虑了一下决定于近期开始同步，还望到时候关注，感谢。

**Comment by kawhicurry** [comment]
由于AOSP的镜像版权受限，南邮镜像站不能同步该镜像。
考虑到镜像站服务器性能及其周边网络环境，代理该镜像也有难度。
建议关闭该issue。

参考：
- [清华大学开源镜像站AOSP帮助](https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/)。
