### ISSUE TITLE
增加Kali Linux镜像

### ISSUE THREAD

**Issue by yjqwyc** [NJUPT-Mirrors-Group/issues#3]
## 开源项目名称及简介
Kali Linux is an open source project that is maintained and funded by Offensive Security, a provider of world-class information security training and penetration testing services.
## 上游镜像名称及简介

* Kali官方 http(s)://http.kali.org

## 其他信息:
  * 镜像大小 321.25 GB （根据USTC）

**Comment by guliujian** [comment]
经过大家的讨论，初步考虑了一下决定于近期开始同步，还望到时候关注，感谢。

**Comment by guliujian** [comment]
已添加完成并完善了帮助文档。
