### ISSUE TITLE
请求添加docker-ce镜像源

### ISSUE THREAD

**Issue by wjbsyc** [NJUPT-Mirrors-Group/issues#4]
## 其他信息:
  * https://docs.docker.com/install/linux/docker-ce/ubuntu/
  * https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/

**Comment by guliujian** [comment]
已添加，相关说明见 `https://mirrors.njupt.edu.cn/help/docker-ce/` ，如果有问题欢迎反馈
