### ISSUE TITLE
请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [NJUPT-Mirrors-Group/issues#5]
最近开发一个项目 https://github.com/ZenithalHourlyRate/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by guliujian** [comment]
可以🙏

**Comment by ZenithalHourlyRate** [comment]
目前 https://mirrorz.org 有了全新的前端，供贵站参考。

贵站参与该项目需要贵站生成一份 `mirrorz.json`，具体格式与要求可以参考项目 README

**Comment by ZenithalHourlyRate** [comment]
参考 https://mirrorz.org/site/NJUPT

目前各站可通过允许其他站使用其数据（对贵站与该项目来说，就是允许 https://mirrorz.org 获取 http://mirrors.njupt.edu.cn/mirrordsync.json 与 http://mirrors.njupt.edu.cn/isoinfo.json ）并编写前端的parser（参考[该目录](https://github.com/tuna/mirrorz/tree/master/src/parser)），使得该数据变为 `mirrorz.json` 的格式，从而能实时反映相关的同步状态。这与之前各站需要提供 `mirrorz.json` 的方式不同。

目前的前端 parser 并不能反应贵站的同步状态，同时相关 `mirrorz.json` 也是[手动生成](https://github.com/tuna/mirrorz/blob/master/scripts/njupt/mirrorz.py)的。注意到贵站的 `mirrordsync.json` 中同步状态较为复杂，希望相关人员能提供相关的 parser。
