### ISSUE TITLE
openEuler镜像源申请加入南京邮电大学开源镜像站

### ISSUE THREAD

**Issue by zhang-jian-jun** [NJUPT-Mirrors-Group/issues#6]
镜像名:
openEuler官方镜像源

上游源（官方镜像）的地址
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

镜像简介
南京邮电大学开源镜像站点，你们好！
我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！

我们提供openEuler镜像同步指令如下:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

openEuler社区基础设施团队
[1]: https://openeuler.org/zh/
[2]: https://repo.openeuler.org/
镜像大小:
多个版本共600G

**Comment by WJHPrince** [comment]
你好，
非常抱歉回复这么晚，经过讨论我们会在近期添加openEuler镜像源，感谢您对我们项目的支持。

**Comment by zhang-jian-jun** [comment]
好的，非常感谢

**Comment by zhang-jian-jun** [comment]
@WJHPrince ,你好，咨询一下，openEuler镜像源添加有进展吗？谢谢支持

**Comment by WJHPrince** [comment]
> @WJHPrince ,你好，咨询一下，openEuler镜像源添加有进展吗？谢谢支持

抱歉，可能最近各位都比较忙，目前日程安排已经加入了对openEuler的计划安排，但是前面还有别的安排需要完成，我们会尽快处理。

**Comment by zhang-jian-jun** [comment]
好的，非常感谢！
