### ISSUE TITLE
请求增加pop os镜像

### ISSUE THREAD

**Issue by largeword** [NJUPT-Mirrors-Group/issues#7]
## 开源项目名称及简介
Pop!_OS
An Operating System by System76
## 上游镜像名称及简介
http://apt.pop-os.org/proprietary/
http://ppa.launchpad.net/system76/pop/ubuntu/
## 其他信息:
  * 镜像大小等

**Comment by kawhicurry** [comment]
国内有个镜像站收录了该镜像，可以考虑一下。
参考：
- [issue](https://github.com/mirrors-tk/feedback/issues/8)
- [help](https://mirrors.tk/help/pop-os/)
- [script](https://github.com/mirrors-tk/conf/blob/master/bin/pop-os.sh)

**Comment by guliujian** [comment]
暂时不考虑添加
