### ISSUE TITLE
请求增加Raspbian（Raspberry Pi OS）软件源

### ISSUE THREAD

**Issue by W-Linus** [NJUPT-Mirrors-Group/issues#8]
## 开源项目名称及简介
Raspbian（Raspberry Pi OS）是树莓派基金会指定的官方系统，因为官方源速度较慢，再加上校内可能使用树莓派的同学较多。希望使用本校镜像站作为更新源，特请求增加此源镜像。
## 上游镜像名称及简介
http://raspbian.raspberrypi.org/raspbian/  此源用于sources.list
https://archive.raspberrypi.org/debian/  此源用于raspi.list
如遇网络问题可以尝试换用中科大或者清华Tuna源以及阿里源
[USTC](https://mirrors.ustc.edu.cn/raspbian/)
[Tuna](https://mirrors.tuna.tsinghua.edu.cn/raspberrypi/)
## 其他信息:
  * 镜像大小等

**Comment by WJHPrince** [comment]
同学你好，

感谢你对南邮镜像站的支持，你的提议我们会加以考虑，如果条件合适，我们会择机将raspbian源和raspberrypi源加入南邮镜像站列表。请耐心等待。

**Comment by kawhicurry** [comment]
镜像大小约80G
参考：
- https://developer.aliyun.com/ask/282594

**Comment by kawhicurry** [comment]
你好，南邮镜像站已添加raspbian软件源。
- 镜像地址：https://mirrors.njupt.edu.cn/raspbian/
- 帮助文档：https://mirrors.njupt.edu.cn/help/raspbian/
