### ISSUE TITLE
请求增加termux软件源

### ISSUE THREAD

**Issue by 2096779623** [NJUPT-Mirrors-Group/issues#9]
## 开源项目名称及简介
Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。
## 上游镜像名称及简介
请看：https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories
## 其他信息:
  * 镜像大小：14.6G(https://github.com/NJUPT-Mirrors-Group/issues/issues/9#issuecomment-1111095977)

**Comment by kawhicurry** [comment]
镜像大小：14.6G
参考：
- https://mirrors.tuna.tsinghua.edu.cn/status/

**Comment by kawhicurry** [comment]
你好，南邮镜像站已添加termux软件源。
- https://mirrors.njupt.edu.cn/termux/
我们已向termux官方团队提交添加镜像的申请，相关的文档也在完善当中，请耐心等待。
